# Generated by Django 4.0.2 on 2022-02-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingredient_owner_alter_ingredientused_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientused',
            name='owner',
        ),
        migrations.AddField(
            model_name='ingredientused',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_used', to='api.meal'),
            preserve_default=False,
        ),
    ]
