# Generated by Django 4.0.2 on 2022-02-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ingredientused_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientused',
            name='meal',
        ),
    ]
