# Generated by Django 4.0.2 on 2022-02-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_ingredientused_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealUsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('using', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.category'),
        ),
        migrations.AlterField(
            model_name='planification',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned', to='api.meal'),
        ),
        migrations.AlterField(
            model_name='planification',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='IngredientUsed',
        ),
        migrations.AddField(
            model_name='mealusing',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usings', to='api.ingredient'),
        ),
        migrations.AddField(
            model_name='mealusing',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used', to='api.meal'),
        ),
    ]
