# Generated by Django 4.0.2 on 2022-02-27 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_alter_ingredient_category_alter_ingredient_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.category'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealusing',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usings', to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='mealusing',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used', to='api.meal'),
        ),
        migrations.AlterField(
            model_name='planification',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned', to='api.meal'),
        ),
        migrations.AlterField(
            model_name='planification',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
